name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello world
      run: echo Hello world $FIRST_NAME $Last_Name - $GITHUB_ACTOR $GITHUB_ACTION $GITHUB_EVENT_NAME!
      env:
        FIRST_NAME: Zou
        Last_Name: Xin
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
